### PR TITLE
feat(pages): project's logo in homepage

### PR DESCRIPTION
**Pull request by wdavidw**
Feel free to enrich amend the list of components. Notes, changing the number of components impact it's disposition depending on the screen size (at the moment, 2 rows of 5 components on smaller screens). CSS grid proprerties must be changed accordingly.

image

### CODE REVIEW

**Review by Edouard-R — APPROVED** [review]

**Comment by wdavidw** [comment]
Someone else wish to review this PR before we merge ?

**Comment by rpignolet** [comment]
> Someone else wish to review this PR before we merge ?

It is holiday, I don't know if we have site validator at DGFiP next week.

**Comment by wdavidw** [comment]
OK, let's wait, not too urgent

**Review by abeguec — APPROVED** [review]
it's ok

**Pull request merged**
