### PR TITLE
chore: remove husky

### PR DESCRIPTION
**Pull request by PaulFarault**
Husky was causing more troubles than it solved. We should replace it by some actions.

### CODE REVIEW

**Review by rpignolet — APPROVED** [review]

**Comment by wdavidw** [comment]
Enforcing scope is volontary to ensure contributors fill an appropriate value present in the [configuration](https://github.com/TOSIT-IO/tdp-website/blob/master/commitlint.config.cjs#L7-L14). Feel free to propose additional scope or to document it in the readme but don't let users create commit history without scope.

**Comment by rpignolet** [comment]
Yes we agree we must verify commit message to check conventional commit but currently we can not commit because husky does not work with a `require` error.

**Comment by wdavidw** [comment]
Could you be more specific on the error message? I believe it is expected.

**Comment by rpignolet** [comment]
Error with husky after running git commit:
```
yarn run v1.22.19
$ /tdp-website/node_modules/.bin/commitlint --edit .git/COMMIT_EDITMSG
/tdp-website/node_modules/cliui/build/index.cjs:291
const stringWidth = require('string-width');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /tdp-website/node_modules/string-width/index.js from /tdp-website/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /tdp-website/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/tdp-website/node_modules/cliui/build/index.cjs:291:21)
    at Object.<anonymous> (/tdp-website/node_modules/yargs/build/index.cjs:1:60678)
    at Object.<anonymous> (/tdp-website/node_modules/yargs/index.cjs:5:30)
    at Object.<anonymous> (/tdp-website/node_modules/@commitlint/cli/lib/cli.js:20:33)
    at Object.<anonymous> (/tdp-website/node_modules/@commitlint/cli/cli.js:2:1) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky - commit-msg hook exited with code 1 (error)
```

**Comment by wdavidw** [comment]
I tried successfully with both npm and yarn, on macos and ubuntu 22.04. What is your Node.js version (`npm --version`)?

**Comment by rpignolet** [comment]
```
$ node --version
v16.19.0
$ yarn --version
1.22.19
$ npm --version
8.19.3
$ npx --version
8.19.3
```

**Comment by wdavidw** [comment]
Node.js 16 is a bit old, 18 or 20 are recommended. In PR #26, I propose to update the readme instructions to only mention NPM.

Speaking about your issue with husky, I run on a fresh Ubuntu 22.04 install the following procedure:

```bash
# Node.js install
curl -L https://bit.ly/n-install | bash
. ~/.bashrc
n 16.19 # 18 or 20 recommended
# Repository
git clone https://github.com/TOSIT-IO/tdp-website.git
cd tdp-website
# NPM
npm install
git add
git add package-lock.json
git commit -m 'invalid message'
```

Could you try to install the latest version of Node.js, for example `n latest` if using [n](https://github.com/tj/n), and remove the `node_module` folder before `npm install`.

**Comment by rpignolet** [comment]
Node updated to latest LTS, same error.
```
$ node --version
v18.18.0
$ npm --version
9.8.1
$ yarn --version
1.22.19
$ npx --version
9.8.1
```

**Pull request closed without merging**
